M48
; DRILL file {KiCad (7.0.0)} date Mon May  8 11:18:23 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-08T11:18:23-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X94.95Y-113.0
T2
X94.0Y-104.0
X94.0Y-128.0
X221.2Y-104.0
X221.2Y-128.0
T1
G00X94.95Y-118.875
M15
G01X94.95Y-119.125
M16
G05
T0
M30
